;/etc/supervisor/conf.d/rempla-messenger-worker.conf
[program:rempla-messenger-consume]
command=php /var/www/remplaclinic.fr/public_html/bin/console messenger:consume async failed scheduler_default --time-limit=3600
user=remplaclk
numprocs=3
startsecs=0
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d

;/etc/supervisor/conf.d/rempla-cron-worker.conf
[program:rempla-cron-consume]
command=php /var/www/remplaclinic.fr/public_html/bin/console messenger:consume scheduler_end_date_checker --time-limit=3600
user=remplaclk
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d